// <auto-generated />
using System;
using Infrasctructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrasctructure.Migrations
{
    [DbContext(typeof(ArciQuizDbContext))]
    partial class ArciQuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Core.Entities.Domanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficolta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FlagErrore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlgDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RispostaA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RispostaB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RispostaC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RispostaD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("RispostaEsatta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Domande");
                });

            modelBuilder.Entity("Core.Entities.Manche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAstensioni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartitaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PenalitaErrore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntiBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoRispostaSecondi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartitaId");

                    b.ToTable("Manches");
                });

            modelBuilder.Entity("Core.Entities.MancheDomanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DomandaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DtEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DtStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MancheId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModificatorePunti")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DomandaId");

                    b.HasIndex("MancheId");

                    b.ToTable("ManchesDomande");
                });

            modelBuilder.Entity("Core.Entities.MancheRispostaRicevuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtRisposta")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MancheDomandaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Risposta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MancheDomandaId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ManchesRisposte");
                });

            modelBuilder.Entity("Core.Entities.Partita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtCreazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Partite");
                });

            modelBuilder.Entity("Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeSquadra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Core.Entities.PlayerPartita", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartitaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "PartitaId");

                    b.HasIndex("PartitaId");

                    b.ToTable("PlayersPartite");
                });

            modelBuilder.Entity("Core.Entities.Manche", b =>
                {
                    b.HasOne("Core.Entities.Partita", "Partita")
                        .WithMany("Manches")
                        .HasForeignKey("PartitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partita");
                });

            modelBuilder.Entity("Core.Entities.MancheDomanda", b =>
                {
                    b.HasOne("Core.Entities.Domanda", "Domanda")
                        .WithMany("Manches")
                        .HasForeignKey("DomandaId");

                    b.HasOne("Core.Entities.Manche", "Manche")
                        .WithMany("Domande")
                        .HasForeignKey("MancheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domanda");

                    b.Navigation("Manche");
                });

            modelBuilder.Entity("Core.Entities.MancheRispostaRicevuta", b =>
                {
                    b.HasOne("Core.Entities.MancheDomanda", "MancheDomanda")
                        .WithMany("Risposte")
                        .HasForeignKey("MancheDomandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MancheDomanda");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Core.Entities.PlayerPartita", b =>
                {
                    b.HasOne("Core.Entities.Partita", "Partita")
                        .WithMany("PlayersPartita")
                        .HasForeignKey("PartitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Player", "Player")
                        .WithMany("IscrizioniPartite")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partita");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Core.Entities.Domanda", b =>
                {
                    b.Navigation("Manches");
                });

            modelBuilder.Entity("Core.Entities.Manche", b =>
                {
                    b.Navigation("Domande");
                });

            modelBuilder.Entity("Core.Entities.MancheDomanda", b =>
                {
                    b.Navigation("Risposte");
                });

            modelBuilder.Entity("Core.Entities.Partita", b =>
                {
                    b.Navigation("Manches");

                    b.Navigation("PlayersPartita");
                });

            modelBuilder.Entity("Core.Entities.Player", b =>
                {
                    b.Navigation("IscrizioniPartite");
                });
#pragma warning restore 612, 618
        }
    }
}
